### ISSUE TITLE
Additional Configuration Paramaters for New Bookmaks

### ISSUE THREAD

**Issue by henri** [davep/tinboard#49]
Feature request to be able to add configuration options and defaults for new bookmarks : 
  - Public or Private by default
  - Read or Unread by default

**Comment by davep** [comment]
Excellent suggestion! I've always configured any client as private/unread so made that the default with Tinboard, but it makes sense to allow for other configurations. Consider it on the TODO list.

**Comment by davep** [comment]
Now part of [v0.14.0](https://github.com/davep/tinboard/releases/tag/v0.14.0); thanks for the suggestion.
